contact_links:
    - name: Support
      url: https://pester.dev/docs/contributing/introduction#where-to-get-support
      about: 'There are many communities available to help you with usage questions.\nSee our recommendations.'