# This is a basic workflow to help you get started with Actions

name: CIdemo

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: Get-ChildItem
        shell: pwsh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          Write-Host "::warning file=app.js,line=1,col=5::this is my first warning"
          Write-Host "::error file=app.js,line=1,col=5::this is bad, much error"
          Write-Host "::group::Some noisy errors"
          Write-Host "::error file=app.js,line=1,col=6::this is bad, much error"
          Write-Host "::error file=app.js,line=1,col=7::this is bad, much error"
          Write-Host "::endgroup::"
