name: LineRewriteDemo
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print countdown
        run: |
          9..4 | % { $c = $_ % 2 ? '|' : 'x'; Write-Host "`r[$c]hello $_" -NoNewline; start-sleep -seconds 1 }
        shell: pwsh

      - name: Print countdown mismatch line
        run: |
          100,20,3 | % { Write-Host "`rhello $_" -NoNewline; Start-Sleep -Seconds 1 }
        shell: pwsh

      - name: Print with output midway
        run: |
          10..5 | % { Write-Host "`rhello $_" -NoNewline; start-sleep -seconds 1; write-output "omg"; Start-Sleep -Seconds 1 }
        shell: pwsh

      - name: Print with host message incl linebreak midway
        run: |
          10..5 | % { Write-Host "`rhello $_" -NoNewline; start-sleep -seconds 1; write-host "omg"; Start-Sleep -Seconds 1 }
        shell: pwsh
