name: PSScriptAnalyzer Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    name: PSScriptAnalyzer Scan
    runs-on: windows-latest
    steps:
        # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: test2.sarif